networks:
  dev:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - dev

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: dev-server
    container_name: dev_server
    tty: true
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: dev-client
    container_name: dev_client
    tty: true
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - dev
